openapi: 3.0.0
info:
  title: "Hourly Weather data Flask REST API"
  description: "An API to explore historical hourly weather observations data from Airport Locations across the US"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Date:
      type: "object"
      required: 
        - date
      properties:
        date:
          type: "string"
    StationID:
      type: "object"
      required: 
        - stationid
      properties:
        stationid:
          type: "string"
  parameters:
    date:
      name: "date"
      description: "Date of the observation to get"
      in: path
      required: True
      schema:
        type: "string"
    stationid:
      name: "stationid"
      description: "StationID of the observation to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /observations:
    get:
      operationId: "observations.get_all_observations_sample"
      tags:
        - "Observations"
      summary: "Read a sample of 100 observations in the database"
      responses:
        "200":
          description: "Succesfully read sample observations data"
  /stations:
    get:
      operationId: "observations.get_all_stations"
      tags:
        - "Stations"
      summary: "Read the list of all stations in the database, with the StationID primary key."
      responses:
        "200":
          description: "Succesfully read stations list"
  /dates:
    get:
      operationId: "observations.get_all_dates"
      tags:
        - "Dates"
      summary: "Read the list of all dates in the database, with the properly formatted Date."
      responses:
        "200":
          description: "Succesfully read dates list"
  /observations/station/{stationid}:
    get:
      operationId: "observations.get_all_stationid"
      tags:
        - StationID
      summary: "Read one station"
      parameters:
        - $ref: "#/components/parameters/stationid"
      responses:
        "200":
          description: "Successfully read one station"
  /observations/date/{date}:
    get:
      operationId: "observations.get_all_date"
      tags:
        - Date
      summary: "Read one date"
      parameters:
        - $ref: "#/components/parameters/date"
      responses:
        "200":
          description: "Successfully read one date"
